# Generated by Django 4.2.7 on 2023-11-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_grades_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assigment',
            new_name='assigment_type',
        ),
    ]
