# Generated by Django 4.2.7 on 2023-12-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_grades_api', '0003_remove_assignature_assignment_assignment_assignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grade',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='presented',
            field=models.BooleanField(null=True),
        ),
    ]
