# Generated by Django 4.2.7 on 2023-12-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_grades_api', '0006_assignature_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='assignature',
        ),
        migrations.AddField(
            model_name='assignature',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignatures', to='school_grades_api.professor'),
        ),
        migrations.AlterField(
            model_name='assignature',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignatures', to='school_grades_api.promotion'),
        ),
    ]
