# Generated by Django 4.2.7 on 2023-12-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_grades_api', '0007_remove_professor_assignature_assignature_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignature',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignatures', to='school_grades_api.promotion'),
        ),
        migrations.AlterField(
            model_name='student',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_grades_api.promotion'),
        ),
    ]
